name: Check

# TODO: check whether runtime generated landing page html has changed

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_NO_WARNINGS: 1
  CI: true

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
      - name: Set up env
        uses: the-guild-org/shared-config/setup@v1
        with:
          node-version-file: .node-version
          install-command: yarn install
      - name: Check
        run: yarn run check:format

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
      - name: Set up env
        uses: the-guild-org/shared-config/setup@v1
        with:
          node-version-file: .node-version
          install-command: yarn install
      - name: Check
        run: yarn run check:lint

  types:
    name: Types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
      - name: Set up env
        uses: the-guild-org/shared-config/setup@v1
        with:
          node-version-file: .node-version
          install-command: yarn install
      - name: 'Generate GraphiQL files'
        run: yarn run build:graphiql
      - name: Check Types
        run: yarn run check:types

  # This is not possible with Bun. TODO: find an alternative
  # missing-peer-deps:
  #   name: Missing peer deps
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
  #     - name: Set up env
  #       uses: the-guild-org/shared-config/setup@v1
  #       with:
  #         node-version-file: .node-version
  #     - name: Check
  #       run: bun run check:missing-peer-deps

  build: # making sure build works so it doesn't fail on us during release
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
      - name: Set up env
        uses: the-guild-org/shared-config/setup@v1
        with:
          node-version-file: .node-version
          install-command: yarn install
      - name: Check
        run: yarn run build
